url: "https://almendra.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "almendra.dev" # the name of your site, e.g. ACME Corp.

# site files are actually under the source directory
source: source

# use collections to do pages
collections:
  pages:
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default 

